namespace Compiler.TablaSimbolos
{
    public enum Categoria
    {
        Identificador,
        NumeroEntero,
        NumeroDecimal,
        Suma,
        Resta,
        Multiplicacion,
        Division,
        Modulo,
        ParentesisAbre,
        ParentesisCierra,
        FinDeArchivo,
        IgualQue,
        DiferenteQue,
        MenorOIgualQue,
        MenorQue,
        MayorOIgualQue,
        MayorQue,
        Asignacion,
        Where,
        From,
        Select,
        Order,
        By,
        Asc,
        Desc,
        Or,
        And
    }
}
